/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze-image'
import { Route as AuthenticatedTranslatorRouteImport } from './routes/_authenticated/translator'
import { Route as AuthenticatedRepliesRouteImport } from './routes/_authenticated/replies'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedNamesRouteImport } from './routes/_authenticated/names'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as AuthenticatedAnalyzerRouteImport } from './routes/_authenticated/analyzer'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/api/analyze-image',
  path: '/api/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTranslatorRoute = AuthenticatedTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepliesRoute = AuthenticatedRepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNamesRoute = AuthenticatedNamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyzerRoute = AuthenticatedAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/images': typeof AuthenticatedImagesRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/names': typeof AuthenticatedNamesRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/replies': typeof AuthenticatedRepliesRoute
  '/translator': typeof AuthenticatedTranslatorRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/images': typeof AuthenticatedImagesRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/names': typeof AuthenticatedNamesRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/replies': typeof AuthenticatedRepliesRoute
  '/translator': typeof AuthenticatedTranslatorRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/analyzer': typeof AuthenticatedAnalyzerRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/names': typeof AuthenticatedNamesRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/_authenticated/replies': typeof AuthenticatedRepliesRoute
  '/_authenticated/translator': typeof AuthenticatedTranslatorRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/admin'
    | '/ads'
    | '/analyzer'
    | '/branding'
    | '/dashboard'
    | '/images'
    | '/listings'
    | '/names'
    | '/posts'
    | '/replies'
    | '/translator'
    | '/api/analyze-image'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/admin'
    | '/ads'
    | '/analyzer'
    | '/branding'
    | '/dashboard'
    | '/images'
    | '/listings'
    | '/names'
    | '/posts'
    | '/replies'
    | '/translator'
    | '/api/analyze-image'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pending'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/ads'
    | '/_authenticated/analyzer'
    | '/_authenticated/branding'
    | '/_authenticated/dashboard'
    | '/_authenticated/images'
    | '/_authenticated/listings'
    | '/_authenticated/names'
    | '/_authenticated/posts'
    | '/_authenticated/replies'
    | '/_authenticated/translator'
    | '/api/analyze-image'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-image': {
      id: '/api/analyze-image'
      path: '/api/analyze-image'
      fullPath: '/api/analyze-image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/translator': {
      id: '/_authenticated/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AuthenticatedTranslatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/replies': {
      id: '/_authenticated/replies'
      path: '/replies'
      fullPath: '/replies'
      preLoaderRoute: typeof AuthenticatedRepliesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/names': {
      id: '/_authenticated/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof AuthenticatedNamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyzer': {
      id: '/_authenticated/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AuthenticatedAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedAnalyzerRoute: typeof AuthenticatedAnalyzerRoute
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedNamesRoute: typeof AuthenticatedNamesRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
  AuthenticatedRepliesRoute: typeof AuthenticatedRepliesRoute
  AuthenticatedTranslatorRoute: typeof AuthenticatedTranslatorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedAnalyzerRoute: AuthenticatedAnalyzerRoute,
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedNamesRoute: AuthenticatedNamesRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
  AuthenticatedRepliesRoute: AuthenticatedRepliesRoute,
  AuthenticatedTranslatorRoute: AuthenticatedTranslatorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  SignupRoute: SignupRoute,
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
